import { db } from "../db";
import { SecurityEvent, Incident } from "../types";
import { detectBruteForce } from "./bruteForce";
import { detectAuthAnomaly } from "./authAnomaly";
import { detectSuspiciousRequest } from "./suspiciousRequest";
import { detectAccessControlBreaches } from "./accessControl";
import { detectRateLimitSpikes } from "./rateLimit";

export interface DetectionEngineOutput {
  createdIncident?: Incident;
  updatedIncident?: Incident;
}

export function processSecurityEvent(event: SecurityEvent): DetectionEngineOutput {
  const recentEvents = db.getSecurityEvents(event.projectId);

  // 1. Run Detection Rules
  const rules = [
    detectBruteForce(event, recentEvents),
    detectAuthAnomaly(event, recentEvents),
    detectSuspiciousRequest(event),
    detectAccessControlBreaches(event, recentEvents),
    detectRateLimitSpikes(event, recentEvents),
  ];

  for (const rule of rules) {
    if (rule.triggered && rule.title && rule.description && rule.severity) {
      // Check if an open incident already exists for this source IP / project
      const existingIncidents = db.getIncidents(event.projectId);
      const matchingOpen = existingIncidents.find(
        (inc) =>
          (inc.status === "OPEN" || inc.status === "INVESTIGATING") &&
          event.sourceIp &&
          inc.sourceIp === event.sourceIp &&
          (inc.title.includes("Brute-Force") || inc.title.includes("Injection") || inc.title.includes("Access"))
      );

      if (matchingOpen) {
        matchingOpen.eventCount += 1;
        matchingOpen.lastSeen = event.timestamp;
        matchingOpen.updatedAt = new Date().toISOString();
        return { updatedIncident: matchingOpen };
      }

      // Otherwise create a new incident
      const newInc = db.createIncident({
        projectId: event.projectId,
        title: rule.title,
        description: rule.description,
        severity: rule.severity,
        status: "OPEN",
        sourceIp: event.sourceIp || null,
        firstSeen: event.timestamp,
        lastSeen: event.timestamp,
        eventCount: rule.matchedEvents ? rule.matchedEvents.length : 1,
        notes: "Automated alert generated by AegisScan Defensive Detection Engine. Ready for analyst triage.",
        projectName: event.projectName,
      });

      return { createdIncident: newInc };
    }
  }

  return {};
}
